export const CARDS_LOADING = 'CARDS_LOADING';
export const GET_CARDS = 'GET_CARDS';
export const GET_ROTATION_CARD = 'GET_ROTATION_CARD';
export const GET_DECK_ID = 'GET_DECK_ID';
export const GET_CARDS_ACTION = 'GET_CARDS_ACTION';
export const GET_ROTATION_CARD_ACTION = 'GET_ROTATION_CARD_ACTION';