export const FETCH_CARDS = "FETCH_CARDS";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAIL = "FETCH_CARDS_FAIL";

export const FETCH_ROTATION = "FETCH_ROTATION";
export const FETCH_ROTATION_SUCCESS = "FETCH_ROTATION_SUCCESS";
export const FETCH_ROTATION_FAIL = "FETCH_ROTATION_FAIL";
