export const CREATE_DECK = "CREATE_DECK";
export const CREATE_DECK_SUCCESS = "CREATE_DECK_SUCCESS";
export const CREATE_DECK_FAIL = "CREATE_DECK_FAIL";

export const SAVE_DECK = "SAVE_DECK";
export const SAVE_DECK_SUCCESS = "SAVE_DECK_SUCCESS";
export const SAVE_DECK_FAIL = "SAVE_DECK_FAIL";
